[package]
name = "nanopre"
version = "0.1.0"
description = "A a zero-dependency, no-unsafe implementation of a minimal C-style text preprocessor."
edition = "2021"
repository = "https://github.com/AlphaModder/nanopre"
license-file = "LICENSE"
readme = "README.md"