[package]
name = "nanopre"
version = "0.1.2"
description = "A a zero-dependency, no-unsafe implementation of a minimal C-style text preprocessor."
edition = "2021"
repository = "https://github.com/AlphaModder/nanopre"
license = "Apache-2.0"
readme = "README.md"